//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProject_Moin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stuff
    {
        public int StuffID { get; set; }
        public string StuffName { get; set; }
        public string EmailAddress { get; set; }
        public string CellPhone { get; set; }
        public string ContactAddress { get; set; }
    }
}
